### ISSUE TITLE
HelpSU is gone, and metadata isn't needed any more

### ISSUE THREAD

**Issue by akkornel** [Stanford/AWS-SSO#3]
Since this was released, HelpSU has disappeared!  So instead, an appropriate ServiceNow link is needed.

Also, when I put in a recent request, I was told that I don't need to provide AWS' metadata.  So, the README should be updated.

Thanks!

**Comment by xueshanf** [comment]
Updated README with new ServiceNow link and removed requirement for AWS SP metadata. Thanks!
